### ISSUE TITLE
Facebook is not initialized

### ISSUE THREAD

**Issue by KarandeepSingh1** [seeden/react-facebook#63]
code:  `<FacebookProvider appId="123456789">
                        <Login
                          scope="email"
                          onResponse={this.handleResponse}
                          onError={this.handleError}
                        >
                          <i className="fa fa-facebook" aria-hidden="true" />
                        </Login>
                      </FacebookProvider>`

Error: Facebook is not initialized
    at Login._callee$ (http://localhost:3001/client/index.js:22717:23)
    at tryCatch (http://localhost:3001/client/index.js:24421:40)
    at Generator.invoke [as _invoke] (http://localhost:3001/client/index.js:24655:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3001/client/index.js:24473:21)
    at step (http://localhost:3001/client/index.js:22008:30)
    at http://localhost:3001/client/index.js:22026:14
    at new Promise (<anonymous>)
    at new F (http://localhost:3001/client/index.js:21878:28)
    at http://localhost:3001/client/index.js:22005:12
    at http://localhost:3001/client/index.js:22786:21

**Comment by mindtonic** [comment]
+1 

Works in development, but when the production build is created, this error starts to appear.

**Comment by seeden** [comment]
Is it showing always in production?

**Comment by MartinCamen** [comment]
I get the same error message.
I'm using Laravel and have the login component mounted in a modal (not a React modal).
When I first render the modal everything runs smoothly and works perfectly. But, if I close the modal and re-open it (re-render the modal's html with the component) I receive the error message.

**Comment by seeden** [comment]
Can you check new version 6.x? I changed whole project.
